import { test } from "node:test";
import assert from "node:assert/strict";
import * as fs from "node:fs";
import * as path from "node:path";
import { SessionStore } from "../src/persist.ts";
import type { Session } from "../src/session.ts";
import { canonicalize, sha256 } from "./golden-canonical.ts";

/**
 * Storage-corpus pins (storage-refactor pre-work, S5).
 *
 * tests/golden/storage-corpus/ holds committed legacy-format session files
 * (generated by scripts/update-storage-corpus.ts through the REAL
 * SessionStore.writeNow path) covering every persisted-record branch:
 * folded blocks, tier-2 supersede, deadRefs tombstones, the fork contract
 * (receipt + retained asymmetry), images, the CCR content-store sibling,
 * twin-namespace files (#2671 ①), and the zstd codec frame.
 *
 * This file pins the CURRENT loadSync round-trip: load each case and digest
 * it against the manifest. When the unified storage lands, the SAME corpus
 * drives old-load → migrate → new-load and these digests must not move.
 * Regeneration is a migration-relevant event: run
 *   node --import tsx scripts/update-storage-corpus.ts
 * and commit the diff with a reason.
 */

process.env.BILI_PERSIST_ZSTD = "0"; // read path is codec-agnostic (magic dispatch); keep construction deterministic

const CORPUS_ROOT = path.resolve(import.meta.dirname, "golden/storage-corpus");

interface CaseResult { description: string; files: string[]; digest: string; notes?: Record<string, unknown> }

const manifest = JSON.parse(fs.readFileSync(path.join(CORPUS_ROOT, "manifest.json"), "utf8")) as Record<string, CaseResult>;

const CASE_META: Record<string, { protocol: string; id: string }> = {
    "folded": { protocol: "anthropic", id: "corpus-folded" },
    "tier2": { protocol: "chat", id: "corpus-tier2" },
    "deadrefs": { protocol: "anthropic", id: "corpus-deadrefs" },
    "fork-receipt": { protocol: "chat", id: "corpus-fork-receipt" },
    "fork-retained": { protocol: "chat", id: "corpus-fork-retained" },
    "image": { protocol: "anthropic", id: "corpus-image" },
    "ccr": { protocol: "responses", id: "corpus-ccr" },
    "twinfile": { protocol: "openai", id: "corpus-twin" },
    "zstd": { protocol: "anthropic", id: "corpus-folded" },
};

/** The canonical digest over a LOADED session — must equal the generator's. */
function sessionDigest(loaded: Session): string {
    return sha256(JSON.stringify(canonicalize({
        id: loaded.id,
        meta: loaded.meta,
        stats: loaded.stats,
        metadata: loaded.metadata,
        state: loaded.state,
        blockContents: [...loaded.blockContents.entries()],
        lastMessages: loaded.lastMessages,
        lastMessagesFolded: loaded.lastMessagesFolded,
        pluginSnapshot: loaded.pluginSnapshot,
        contentStore: loaded.contentStore,
    })));
}

function loadCase(name: string): Session {
    const meta = CASE_META[name]!;
    // Reading a BILIZSTD1-framed file needs the codec constructed
    // (compress:false → createStorageCodec undefined → plain-only reader;
    // decode itself dispatches on magic, so the reader codec is safe).
    const prevZstd = process.env.BILI_PERSIST_ZSTD;
    if (name === "zstd") process.env.BILI_PERSIST_ZSTD = "1";
    try {
        const store = new SessionStore({ dir: path.join(CORPUS_ROOT, name), debounceMs: 1, enabled: true });
        const loaded = store.loadSync(meta.id, { protocol: meta.protocol, upstreamOrigin: "http://127.0.0.1:8199" });
        assert.ok(loaded, `${name}: loadSync returned null`);
        return loaded;
    } finally {
        if (prevZstd === undefined) delete process.env.BILI_PERSIST_ZSTD;
        else process.env.BILI_PERSIST_ZSTD = prevZstd;
    }
}

test("storage corpus: manifest covers every case file (no orphans)", () => {
    const listed = new Set<string>();
    for (const [name, c] of Object.entries(manifest)) for (const f of c.files) listed.add(path.join(name, f));
    const onDisk: string[] = [];
    const walk = (d: string): void => {
        for (const e of fs.readdirSync(d, { withFileTypes: true })) {
            const full = path.join(d, e.name);
            if (e.isDirectory()) walk(full);
            else onDisk.push(path.relative(CORPUS_ROOT, full));
        }
    };
    walk(CORPUS_ROOT);
    for (const f of onDisk) {
        if (f === "manifest.json") continue;
        assert.ok(listed.has(f), `orphaned corpus file not listed in manifest: ${f}`);
    }
    assert.equal(onDisk.length, [...listed].length + 1, "manifest lists a file that is not on disk");
});

test("storage corpus: every case round-trips to its pinned digest", () => {
    for (const [name, entry] of Object.entries(manifest)) {
        const loaded = loadCase(name);
        assert.equal(sessionDigest(loaded), entry.digest, `${name}: round-trip digest drifted — regeneration or migration changed loadSync semantics`);
    }
});

test("storage corpus: tier2 #401 normalization — byte-identical one/full collapses, distinct one survives", () => {
    const s = loadCase("tier2");
    let collapsed = 0;
    let distinct = 0;
    for (const [bid, content] of s.blockContents) {
        if (content.one === null) collapsed++;
        else distinct++;
        assert.ok(typeof content.full.text === "string" && content.full.text.length > 0, `${bid}: full view must survive load`);
    }
    assert.ok(collapsed >= 1, "the byte-identical pair must be normalized to one:null on load (#401)");
    assert.ok(distinct >= 1, "the ACTIVE tier-2 block's distinct one-line view must survive load");
    const active = s.state.blocks.filter((b) => b.active);
    assert.ok(active.length >= 1, "tier2: an active tier-2 block must exist");
});

test("storage corpus: deadrefs tombstones + ghost refs survive the round-trip", () => {
    const s = loadCase("deadrefs");
    const ghostRef = manifest["deadrefs"]!.notes!.ghostRef as string;
    assert.ok((s.state.deadRefs ?? []).includes(ghostRef), `deadRefs must contain the pinned ghost ${ghostRef} after reload (#2362/#2370)`);
    assert.ok(s.state.messageRefs.byRef[ghostRef] !== undefined, "ghost ref must KEEP its raw-id mapping (Kernel Contract: refs never reassigned)");
});

test("storage corpus: fork contract — receipt keeps store, retained-only DROPS it (#2675 ② asymmetry)", () => {
    const receipt = loadCase("fork-receipt");
    assert.ok(Array.isArray(receipt.pluginSnapshot) && receipt.pluginSnapshot.length > 0, "receipt: pluginSnapshot must persist");
    assert.ok(receipt.contentStore, "receipt: forkContentStore must persist into contentStore on load");
    assert.ok(Array.isArray(receipt.metadata.publicSnapshotStoredRefs) && (receipt.metadata.publicSnapshotStoredRefs as unknown[]).length > 0, "receipt: publicSnapshotStoredRefs union must persist");

    const retained = loadCase("fork-retained");
    assert.ok(Array.isArray(retained.pluginSnapshot) && retained.pluginSnapshot.length > 0, "retained: pluginSnapshot must persist");
    assert.equal(retained.contentStore, undefined, "retained-only: forkContentStore is DROPPED by buildRecord — this verbatim asymmetry is why #2675 ② exists");
});

test("storage corpus: image case carries base64 media + image stats", () => {
    const s = loadCase("image");
    const img = s.lastMessages?.find((m) => (m as { contentType?: string }).contentType === "image");
    assert.ok(img, "image message must survive in the persisted tail");
    assert.equal(s.stats.imageShrunkCount, 1);
    assert.ok(Array.isArray(s.metadata.imageShrinks), "imageShrinks metadata must survive");
});

test("storage corpus: ccr sibling file holds the two #1097 originals", () => {
    const files = manifest["ccr"]!.files;
    const sibling = files.find((f) => f.endsWith(".content-store.json"));
    assert.ok(sibling, `ccr case must ship a content-store.json sibling (files: ${files.join(", ")})`);
    const parsed = JSON.parse(fs.readFileSync(path.join(CORPUS_ROOT, "ccr", sibling), "utf8")) as { byRef?: Record<string, unknown>; byHash?: Record<string, string> };
    assert.equal(Object.keys(parsed.byRef ?? {}).length, 2, "both CCR originals must be in the sibling store");
    assert.equal(Object.keys(parsed.byHash ?? {}).length, 2);
});

test("storage corpus: twinfile — namespaced wins with meta, flat fallback without (#2671 ①)", () => {
    const notes = manifest["twinfile"]!.notes!;
    const viaMeta = loadCase("twinfile");
    assert.equal(viaMeta.stats.requests, notes.namespacedRequests, "with protocol meta the namespaced v2 record must win");

    const store = new SessionStore({ dir: path.join(CORPUS_ROOT, "twinfile"), debounceMs: 1, enabled: true });
    const viaFlat = store.loadSync("corpus-twin");
    assert.ok(viaFlat, "flat legacy twin must remain loadable through the kernel flat-name fallback");
    assert.equal(viaFlat.stats.requests, notes.flatTwinRequests, "without meta the STALE flat v1 twin is what the fallback finds");
    assert.equal(sessionDigest(viaFlat), notes.flatFallbackDigest, "flat fallback digest must match the pinned value");
});

test("storage corpus: zstd-framed twin loads to the IDENTICAL digest as plain JSON", () => {
    assert.equal(manifest["zstd"]!.digest, manifest["folded"]!.digest, "codec framing must not change loadSync semantics");
    const z = loadCase("zstd");
    assert.equal(sessionDigest(z), manifest["folded"]!.digest, "zstd case must decode to the folded digest");
});
