export const WEB_CLIENT = `
const byId=(id)=>document.getElementById(id);let routeState="disabled";
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function toast(message,error){const node=byId("toast");node.textContent=message;node.className="toast show"+(error?" err":"");setTimeout(()=>node.className="toast"+(error?" err":""),2600)}
function busy(button,on,label){if(!button)return;if(on){button.dataset.label=button.textContent;button.textContent=label||"处理中…";button.disabled=true;return}if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}button.disabled=false}
async function json(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||data.detail||("HTTP "+response.status));return data}
function showPage(name){document.querySelectorAll(".page").forEach((node)=>node.classList.toggle("active",node.id==="page-"+name));document.querySelectorAll(".nav button").forEach((node)=>node.classList.toggle("active",node.dataset.page===name));if(name==="sessions")loadSessions();if(name==="routing")loadRouting();if(name==="upstream"){loadUpstream();loadOverrides()}}
document.querySelectorAll(".nav button").forEach((button)=>button.addEventListener("click",()=>showPage(button.dataset.page)));
async function loadConfig(){const data=await json("/__bili/config");byId("providers-json").value=JSON.stringify(data.providers||{},null,2);byId("proxy-url").value=data.upstreamProxy||"";document.querySelectorAll('input[name="proxy-mode"]').forEach((input)=>input.checked=input.value===(data.upstreamProxyMode||"direct"));return data}
async function loadRouting(){try{const data=await json("/__bili/codex");routeState=data.state;const badge=byId("route-badge");const used=data.state==="enabled"&&data.lastRequestAt;badge.className="badge "+(data.state==="enabled"?(used?"ok":"warn"):data.state==="conflict"?"err":"");badge.textContent=data.state==="enabled"?(used?"使用中":"等待首次请求"):data.state==="conflict"?"配置冲突":"未启用";byId("route-provider").textContent=data.providerId||(data.provider&&data.provider.id)||"—";byId("route-real").textContent=data.originalBaseUrl||(data.provider&&data.provider.baseUrl)||"—";byId("route-local").textContent=data.baseUrl||"—";byId("route-detail").textContent=data.detail||(data.state==="enabled"&&!used?"若当前 Codex 尚未接入，可重新打开 Codex。":"");const button=byId("route-toggle");button.textContent=data.state==="disabled"?"启用 Codex 路由":"恢复原配置";button.className="btn "+(data.state==="disabled"?"primary":"danger");button.disabled=false}catch(error){byId("route-detail").textContent=String(error)}}
async function toggleRoute(){const button=byId("route-toggle");const action=routeState==="disabled"?"enable":"disable";busy(button,true,action==="enable"?"启用中…":"恢复中…");try{const data=await json("/__bili/codex/"+action,{method:"POST"});busy(button,false);await loadRouting();toast(data.detail||(action==="enable"?"Codex 路由已启用":"原配置已恢复"))}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function copyRoute(){const button=byId("copy-route");busy(button,true,"复制中…");try{await navigator.clipboard.writeText(byId("route-local").textContent);toast("路由地址已复制")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadUpstream(){try{const data=await json("/__bili/upstream");const labels={"provider":"Provider 单独代理","provider-direct":"Provider 直连","bili-env":"BILI_UPSTREAM_PROXY","web-manual":"Web 手动代理","config":"配置文件代理","HTTPS_PROXY":"HTTPS_PROXY","HTTP_PROXY":"HTTP_PROXY","ALL_PROXY":"ALL_PROXY","windows-system":"Windows 系统代理","windows-bypass":"Windows 绕过列表","no-proxy":"NO_PROXY","direct":"直连"};byId("upstream-source").textContent=labels[data.source]||data.source||"直连";byId("upstream-effective").textContent=data.proxy||"direct";byId("upstream-pac").textContent=data.autoConfigUrl||"—";const state=byId("upstream-state");state.className="status "+(data.connected===true?"ok":data.connected===false?"err":"");state.textContent=data.connected===true?"CONNECT 正常":data.connected===false?(data.error||"连接失败"):"尚未观察到上游连接"}catch(error){byId("upstream-state").textContent=String(error)}}
async function saveUpstream(){const button=byId("save-upstream");busy(button,true,"保存中…");const mode=document.querySelector('input[name="proxy-mode"]:checked').value;try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({upstreamProxyMode:mode,upstreamProxy:byId("proxy-url").value.trim()||null})});toast("上游设置已热更新");await loadUpstream()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function testUpstream(){const button=byId("test-upstream");busy(button,true,"测试中…");try{const data=await json("/__bili/upstream/test",{method:"POST"});toast("连接成功，HTTP "+data.status);await loadUpstream()}catch(error){toast(String(error),true);await loadUpstream()}finally{busy(button,false)}}
async function loadHistory(){try{const data=await json("/__bili/codex-history");byId("history-summary").textContent="当前分桶："+data.targetProviderId+"\\n检测到旧版 bili 路由会话："+data.sessions+"（"+data.jsonlFiles+" 个 JSONL，"+data.stateRows+" 条 state DB）";byId("repair-history").disabled=data.sessions===0&&data.stateRows===0;if(data.stateDbError)byId("history-summary").textContent+="\\n"+data.stateDbError;return data}catch(error){byId("history-summary").textContent=String(error);throw error}}
async function previewHistory(){const button=byId("preview-history");busy(button,true,"预览中…");try{await loadHistory();toast("历史记录预览已刷新")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function repairHistory(){const button=byId("repair-history");if(!confirm("将先备份，再把确认属于旧 bili 路由的会话迁移到当前 provider。继续？"))return;busy(button,true,"修复中…");let result;try{result=await json("/__bili/codex-history/repair",{method:"POST"});toast("历史记录已修复，备份："+result.backupPath)}catch(error){toast(String(error),true)}finally{busy(button,false)}if(result)await loadHistory().catch(()=>{})}
async function saveProviders(){const button=byId("save-providers");busy(button,true,"保存中…");try{const providers=JSON.parse(byId("providers-json").value);await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("Provider 配置已热更新")}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadOverrides(){try{const data=await loadConfig();const providers=data.providers||{};const box=byId("upstream-overrides");const entries=Object.entries(providers);if(entries.length===0){box.innerHTML='<p class="status">暂无 Provider。在"高级设置"页添加 Provider 后可在此按 URL 配置代理。</p>';return}box.innerHTML='<table><thead><tr><th>Provider URL</th><th>上游代理（空=继承全局）</th></tr></thead><tbody>'+entries.map(([url,route])=>'<tr><td class="mono">'+escapeHtml(url)+'</td><td><input class="mono override-proxy" data-url="'+escapeHtml(url)+'" value="'+escapeHtml((route&&route.proxy)||"")+'" placeholder="继承全局"></td></tr>').join("")+'</tbody></table>'}catch(error){byId("upstream-overrides").textContent=String(error)}}
async function saveOverrides(){const button=byId("save-overrides");busy(button,true,"保存中…");try{const data=await loadConfig();const providers=data.providers||{};document.querySelectorAll(".override-proxy").forEach((input)=>{const url=input.dataset.url;if(!url)return;if(!providers[url])providers[url]={};const val=input.value.trim();if(val)providers[url].proxy=val;else delete providers[url].proxy});await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast("按 URL 覆盖已热更新");await loadOverrides()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadSessions(){try{const data=await json("/__bili/stats");const rows=(data.sessions||[]).map((item)=>"<tr><td>"+escapeHtml(item.title||"—")+"</td><td>"+escapeHtml(item.protocol||"—")+"</td><td class=mono>"+escapeHtml(item.label||"—")+"</td><td>"+escapeHtml(item.requests)+"</td><td>"+escapeHtml(item.contextTokens)+"</td><td>"+escapeHtml(new Date(item.lastSeen).toLocaleString())+"</td></tr>").join("");byId("sessions-body").innerHTML=rows||'<tr><td colspan="6">暂无会话</td></tr>'}catch(error){toast(String(error),true);throw error}}
async function refreshSessions(){const button=byId("refresh-sessions");busy(button,true,"刷新中…");try{await loadSessions();toast("会话列表已刷新")}catch{}finally{busy(button,false)}}
byId("route-toggle").addEventListener("click",toggleRoute);byId("copy-route").addEventListener("click",copyRoute);document.querySelectorAll(".copy-btn").forEach((btn)=>btn.addEventListener("click",async()=>{busy(btn,true,"复制中…");try{await navigator.clipboard.writeText(btn.dataset.copy||"");toast("已复制")}catch(e){toast(String(e),true)}finally{busy(btn,false)}}));byId("save-upstream").addEventListener("click",saveUpstream);byId("test-upstream").addEventListener("click",testUpstream);byId("preview-history").addEventListener("click",previewHistory);byId("repair-history").addEventListener("click",repairHistory);byId("save-providers").addEventListener("click",saveProviders);byId("save-overrides").addEventListener("click",saveOverrides);byId("refresh-sessions").addEventListener("click",refreshSessions);
Promise.all([loadConfig(),loadRouting(),loadUpstream(),loadHistory()]).catch((error)=>toast(String(error),true));setInterval(()=>{if(byId("page-sessions").classList.contains("active"))loadSessions().catch(()=>{})},5000);
`;
