import { WEB_CLIENT } from "./client.js";
import { WEB_STYLES } from "./styles.js";

export function renderPage(origin: string, version: string): string {
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>billion-context</title><style>${WEB_STYLES}</style></head><body>
<div class="app"><aside class="sidebar"><div class="brand">billion<span>-context</span><span class="version">v${version} · ${origin}</span></div><nav class="nav"><button class="active" data-page="overview">概览</button><button data-page="routing">路由</button><button data-page="upstream">上游</button><button data-page="sessions">会话</button><button data-page="settings">设置</button></nav></aside>
<main class="main"><section id="page-overview" class="page active"><h1>概览</h1><p class="lead">本地路由与上游网络相互独立，ACP 压缩运行在两者之间。</p><div class="grid"><div class="card"><h2>服务地址</h2><p class="mono">${origin}</p></div><div class="card"><h2>Codex 路由</h2><p class="status">在“路由”页接管当前 Codex Provider，不改变历史分桶。</p></div></div></section>
<section id="page-routing" class="page"><h1>Codex 路由</h1><p class="lead">Local Route Takeover 是 Codex Desktop 的正式接入方式；MITM 仅用于硬编码 endpoint 客户端。</p><div class="card"><div class="card-head"><h2>路由启用</h2><span class="badge ok">服务运行中</span></div><dl class="kv"><dt>路由总开关</dt><dd>● ON</dd><dt>Codex</dt><dd id="route-codex-switch">加载中</dd><dt>Claude</dt><dd>○ 未启用</dd><dt>Gemini</dt><dd>○ 未启用</dd><dt>服务地址</dt><dd class="mono">${origin}</dd></dl></div><div class="card"><div class="card-head"><h2>本地路由</h2><span id="route-badge" class="badge">加载中</span></div><dl class="kv"><dt>当前 Provider</dt><dd id="route-provider" class="mono">—</dd><dt>真实端点</dt><dd id="route-real" class="mono">—</dd><dt>路由端点</dt><dd id="route-local" class="mono">—</dd><dt>模式</dt><dd>● 本地路由（推荐）　○ 透明代理 MITM（fallback）</dd></dl><div id="route-detail" class="notice"></div><div class="actions"><button id="route-toggle" class="btn primary">启用 Codex 路由</button><button id="copy-route" class="btn">复制地址</button></div></div>
<div class="card"><div class="card-head"><h2>历史记录</h2></div><div id="history-summary" class="status">加载中</div><div class="actions"><button id="preview-history" class="btn">预览</button><button id="repair-history" class="btn danger">修复旧版路由会话</button></div></div></section>
<section id="page-upstream" class="page"><h1>上游网络</h1><p class="lead">控制 bili 如何访问真实 Provider，不会改变 Codex 的本地路由地址。</p><div class="card"><div class="modes"><label><input type="radio" name="proxy-mode" value="auto" checked>自动</label><label><input type="radio" name="proxy-mode" value="manual">手动</label><label><input type="radio" name="proxy-mode" value="direct">直连</label></div><div class="field"><label>HTTP / HTTPS Proxy</label><input id="proxy-url" class="mono" placeholder="http://127.0.0.1:7897"></div><dl class="kv"><dt>当前来源</dt><dd id="upstream-source">自动</dd><dt>有效代理</dt><dd id="upstream-effective" class="mono">direct</dd><dt>系统 PAC</dt><dd id="upstream-pac" class="mono">—</dd><dt>状态</dt><dd id="upstream-state" class="status">尚未测试</dd></dl><div class="actions"><button id="save-upstream" class="btn primary">保存并热更新</button><button id="test-upstream" class="btn">测试连接</button></div></div><div class="card"><div class="card-head"><h2>高级设置</h2></div><dl class="kv"><dt>全局上游代理</dt><dd id="upstream-global-mode">自动</dd><dt>按 Provider 覆盖</dt><dd id="upstream-provider-override" class="mono">—</dd></dl><p class="status">具体 URL 覆盖在“设置”页的 providers JSON 中维护，保存后立即热更新。</p></div></section>
<section id="page-sessions" class="page"><div class="card-head"><div><h1>会话</h1><p class="lead">ACP 压缩状态与上游用量。</p></div><button id="refresh-sessions" class="btn">刷新</button></div><div class="card"><table><thead><tr><th>标题</th><th>协议</th><th>标识</th><th>请求</th><th>上下文</th><th>最后活动</th></tr></thead><tbody id="sessions-body"></tbody></table></div></section>
<section id="page-settings" class="page"><h1>设置</h1><p class="lead">按 URL 的 Provider 覆盖配置；保存后立即热更新。</p><div class="card"><div class="field"><label>providers JSON</label><textarea id="providers-json">{}</textarea></div><div class="actions"><button id="save-providers" class="btn primary">保存并应用</button></div></div></section></main></div><div id="toast" class="toast"></div><script>${WEB_CLIENT}</script></body></html>`;
}
