import { WEB_CLIENT } from "./client.js";
import { WEB_STYLES } from "./styles.js";

export function renderPage(origin: string, version: string): string {
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>billion-context</title><style>${WEB_STYLES}</style></head><body>
<div class="app"><aside class="sidebar"><div class="brand">billion<span>-context</span><span class="version">v${version} · ${origin}</span></div><nav class="nav"><button class="active" data-page="overview">概览</button><button data-page="routing">接入</button><button data-page="upstream">上游</button><button data-page="sessions">会话</button><button data-page="settings">设置</button></nav></aside>
<main class="main"><section id="page-overview" class="page active"><h1>概览</h1><p class="lead">本地路由与上游网络相互独立，ACP 压缩运行在两者之间。</p><div class="grid"><div class="card"><h2>服务地址</h2><p class="mono">${origin}</p></div><div class="card"><h2>客户端接入</h2><p class="status">在"接入"页将各客户端（Codex / Claude Code / OpenCode / Pi 等）的流量路由到 bili。</p></div></div></section>
<section id="page-routing" class="page"><h1>客户端接入</h1><p class="lead">两类接入：A. API-key 客户端加 <span class="mono">/bili/</span> 前缀（零配置）；B. 订阅/登录客户端用 MITM 或路由接管。同一客户端两种方式都可能用到。</p>
<h2 class="section-title">A. API-key 客户端（/bili/ 前缀）</h2>
<p class="hint">在客户端配置里把原 baseURL 前加上 <span class="mono">${origin}/bili/</span> 即可，其余不变。上下文窗口默认按模型名匹配内置表，可在「设置」页的 providers JSON 里按 URL + 模型精确覆盖。</p>
<div class="card"><div class="card-head"><h2>OpenCode</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://open.bigmodel.cn/api/coding/paas/v4">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.config/opencode/opencode.json</dd><dt>baseURL</dt><dd class="mono">${origin}/bili/https://open.bigmodel.cn/api/coding/paas/v4</dd></dl></div>
<div class="card"><div class="card-head"><h2>Codex（API key）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.openai.com/v1">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.codex/config.toml</dd><dt>base_url</dt><dd class="mono">${origin}/bili/https://api.openai.com/v1</dd></dl></div>
<div class="card"><div class="card-head"><h2>Pi</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.anthropic.com">复制</button></div><dl class="kv"><dt>配置文件</dt><dd class="mono">~/.pi/agent/models.json</dd><dt>baseUrl</dt><dd class="mono">${origin}/bili/https://api.anthropic.com</dd></dl></div>
<div class="card"><div class="card-head"><h2>Claude Code（API key）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/https://api.anthropic.com">复制</button></div><dl class="kv"><dt>环境变量</dt><dd class="mono">ANTHROPIC_BASE_URL=${origin}/bili/https://api.anthropic.com</dd></dl></div>
<div class="card"><div class="card-head"><h2>通用（Cursor / Aider / Continue）</h2><button class="btn small copy-btn" data-copy="${origin}/bili/">复制</button></div><dl class="kv"><dt>规则</dt><dd>任意 baseURL 前加 <span class="mono">${origin}/bili/</span></dd><dt>示例</dt><dd class="mono">${origin}/bili/https://api.openai.com/v1</dd></dl></div>
<h2 class="section-title">B. 订阅/登录客户端（手动配置 / MITM）</h2>
<p class="hint">Codex 订阅可通过手动改 config.toml 路由；硬编码 endpoint 的 OAuth 客户端（Claude Code / ZCode）需 MITM 透明代理。</p>
<div class="card"><div class="card-head"><h2>Codex（ChatGPT 订阅）</h2></div><p class="hint">在 <code>~/.codex/config.toml</code> 中添加以下配置，将 Codex 订阅流量路由到 bili（与其他客户端格式统一）：</p><pre class="config-block"><code>openai_base_url = "${origin}/bili/https://chatgpt.com/backend-api/codex"</code></pre><div class="actions"><button class="btn copy-btn" data-copy="openai_base_url = &quot;${origin}/bili/https://chatgpt.com/backend-api/codex&quot;">复制配置</button></div><p class="hint">⚠️ 如果之前用过 bili 的自动启用功能，请手动从 config.toml 中删除 bili 添加的 <code>[model_providers.openai]</code> 段或旧的 <code>openai_base_url</code> 行。</p></div>
<div class="card"><div class="card-head"><h2>Claude Code（订阅）</h2><span class="badge">MITM</span></div><dl class="kv"><dt>方式</dt><dd>MITM 透明代理（拦截 HTTPS）</dd><dt>HTTP Proxy</dt><dd class="mono">${origin}</dd><dt>环境变量</dt><dd class="mono">HTTPS_PROXY=${origin}<br>NODE_EXTRA_CA_CERTS=~/.local/share/billion-context/ca/root-ca.pem</dd></dl></div>
<div class="card"><div class="card-head"><h2>ZCode（编程套餐）</h2><span class="badge">MITM</span></div><dl class="kv"><dt>方式</dt><dd>MITM 透明代理</dd><dt>设置</dt><dd>Settings → Network → HTTP Proxy = <span class="mono">${origin}</span></dd><dt>CA 证书</dt><dd class="mono">~/.local/share/billion-context/ca/root-ca.pem</dd></dl></div>
<div class="card"><div class="card-head"><h2>Codex 历史记录</h2></div><div id="history-summary" class="status">加载中</div><div class="actions"><button id="preview-history" class="btn">预览</button><button id="repair-history" class="btn danger">修复旧版路由会话</button></div></div></section>
<section id="page-upstream" class="page"><h1>上游网络</h1><p class="lead">控制 bili 如何访问真实 Provider，不会改变客户端的本地路由地址。</p><div class="card"><div class="card-head"><h2>全局代理</h2></div><div class="modes"><label><input type="radio" name="proxy-mode" value="direct" checked>直连（默认）</label><label><input type="radio" name="proxy-mode" value="manual">手动代理</label><label><input type="radio" name="proxy-mode" value="auto">自动（跟随系统）</label></div><div class="field"><label>HTTP / HTTPS Proxy</label><input id="proxy-url" class="mono" placeholder="http://127.0.0.1:7897"></div><dl class="kv"><dt>当前来源</dt><dd id="upstream-source">直连</dd><dt>有效代理</dt><dd id="upstream-effective" class="mono">direct</dd><dt>系统 PAC</dt><dd id="upstream-pac" class="mono">—</dd><dt>状态</dt><dd id="upstream-state" class="status">尚未测试</dd></dl><div class="actions"><button id="save-upstream" class="btn primary">保存并热更新</button><button id="test-upstream" class="btn">测试连接</button></div></div><div class="card"><div class="card-head"><h2>按 URL 覆盖</h2></div><p class="status">为特定 Provider 单独设置上游代理，覆盖全局设置。留空 = 继承全局。</p><div id="upstream-overrides" class="status">加载中</div><div class="actions"><button id="save-overrides" class="btn primary">保存覆盖并热更新</button></div></div></section>
<section id="page-sessions" class="page"><div class="card-head"><div><h1>会话</h1><p class="lead">ACP 压缩状态与上游用量。</p></div><button id="refresh-sessions" class="btn">刷新</button></div><div class="card"><table><thead><tr><th>标题</th><th>协议</th><th>标识</th><th>请求</th><th>上下文</th><th>最后活动</th></tr></thead><tbody id="sessions-body"></tbody></table></div></section>
<section id="page-settings" class="page"><h1>高级设置</h1><p class="lead">直接编辑 providers JSON（添加新 Provider、配置模型上下文窗口、按 URL 代理等）；保存后立即热更新。</p><div class="card"><div class="field"><label>providers JSON</label><textarea id="providers-json">{}</textarea></div><div class="actions"><button id="save-providers" class="btn primary">保存并应用</button></div></div></section></main></div><div id="toast" class="toast"></div><script>${WEB_CLIENT}</script></body></html>`;
}
